import chromium from "@sparticuz/chromium";
import puppeteer from "puppeteer-core";

function cleanUsername(value = "") {
  return String(value).trim().replace(/^@/, "").replace(/[^A-Za-z0-9._]/g, "").slice(0, 64);
}

function twoLetter(v) {
  return typeof v === "string" && /^[A-Za-z]{2}$/.test(v) ? v.toUpperCase() : null;
}

function scanRegionFields(obj, maxHits = 30) {
  const hits = [];
  const seen = new WeakSet();

  const walk = (value, path = "", depth = 0) => {
    if (!value || typeof value !== "object" || depth > 7 || hits.length >= maxHits) return;
    if (seen.has(value)) return;
    seen.add(value);

    for (const [key, child] of Object.entries(value)) {
      const nextPath = path ? `${path}.${key}` : key;
      if (/region|locationcreated|country/i.test(key) && ["string", "number", "boolean"].includes(typeof child)) {
        hits.push({ path: nextPath, value: String(child).slice(0, 120) });
      }
      if (child && typeof child === "object") walk(child, nextPath, depth + 1);
      if (hits.length >= maxHits) break;
    }
  };

  walk(obj);
  return hits;
}

export default async function handler(req, res) {
  res.setHeader("Content-Type", "application/json; charset=utf-8");
  res.setHeader("Cache-Control", "no-store");

  if (req.method !== "GET") return res.status(405).json({ error: "Vain GET-pyyntö on sallittu." });

  const username = cleanUsername(req.query.username);
  if (!username) return res.status(400).json({ error: "Virheellinen TikTok-käyttäjänimi." });

  let browser;

  try {
    browser = await puppeteer.launch({
      args: chromium.args,
      defaultViewport: { width: 1280, height: 900 },
      executablePath: await chromium.executablePath(),
      headless: chromium.headless,
    });

    const page = await browser.newPage();
    await page.setUserAgent(
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
    );
    await page.setExtraHTTPHeaders({ "Accept-Language": "en-US,en;q=0.9" });

    const profileUrl = `https://www.tiktok.com/@${encodeURIComponent(username)}`;

    // Listen BEFORE navigation. We prefer the request generated by TikTok's own frontend
    // over constructing /api/post/item_list/ ourselves. This preserves the browser session,
    // cookies and any parameters that TikTok's page itself adds to the request.
    let capturedPostResponse = null;
    let resolvePostCapture;
    const postCapturePromise = new Promise((resolve) => { resolvePostCapture = resolve; });

    const onResponse = async (networkResponse) => {
      try {
        const url = networkResponse.url();
        if (!/\/api\/post\/item_list\//.test(url) || capturedPostResponse) return;

        const status = networkResponse.status();
        const text = await networkResponse.text();
        let data = null;
        try { data = JSON.parse(text); } catch {}

        capturedPostResponse = { url, status, text, data };
        resolvePostCapture(capturedPostResponse);
      } catch {
        // Ignore individual response parsing errors and keep listening.
      }
    };

    page.on("response", onResponse);

    const response = await page.goto(profileUrl, { waitUntil: "domcontentloaded", timeout: 20000 });

    const parsed = await page.evaluate(() => {
      const el = document.querySelector("#__UNIVERSAL_DATA_FOR_REHYDRATION__");
      if (!el?.textContent) {
        return { user: null, stats: null, rawRegion: null, regionKeyPresent: false };
      }

      try {
        const data = JSON.parse(el.textContent);
        const info = data?.__DEFAULT_SCOPE__?.["webapp.user-detail"]?.userInfo;
        const user = info?.user || null;
        return {
          user,
          stats: info?.stats || info?.statsV2 || null,
          regionKeyPresent: !!user && Object.prototype.hasOwnProperty.call(user, "region"),
          rawRegion: user && Object.prototype.hasOwnProperty.call(user, "region") ? user.region : null,
        };
      } catch {
        return { user: null, stats: null, rawRegion: null, regionKeyPresent: false };
      }
    });

    if (!parsed.user) {
      return res.status(404).json({ error: "TikTok ei palauttanut julkista profiilidataa tästä sivusta." });
    }

    const u = parsed.user;
    const s = parsed.stats || {};

    // Give TikTok's own frontend a chance to request the user's post list. A small scroll
    // helps lazy-loaded profile grids start their normal browser request when available.
    try {
      await page.evaluate(() => window.scrollTo(0, Math.max(document.body.scrollHeight * 0.45, 700)));
    } catch {}

    try {
      await Promise.race([
        postCapturePromise,
        new Promise((resolve) => setTimeout(resolve, 9000)),
      ]);
    } catch {}

    page.off("response", onResponse);

    const parseItems = (data) => {
      if (!data || typeof data !== "object") return [];
      if (Array.isArray(data.itemList)) return data.itemList;
      if (Array.isArray(data.items)) return data.items;
      if (Array.isArray(data?.body?.itemListData)) return data.body.itemListData;
      return [];
    };

    const makePostResult = (source, httpStatus, data, text, error = null) => {
      const items = parseItems(data);
      const item = items[0] || null;
      const id = item ? (item.id || item.itemId || item?.itemStruct?.id || null) : null;
      const unique = u.uniqueId || username;
      const regionLikeFields = item ? scanRegionFields(item) : [];

      return {
        attempted: true,
        source,
        httpStatus,
        ok: items.length > 0,
        itemCount: items.length,
        firstVideoId: id ? String(id) : null,
        firstVideoUrl: id ? `https://www.tiktok.com/@${encodeURIComponent(unique)}/video/${id}` : null,
        locationCreated: item?.locationCreated ?? item?.location_created ?? item?.itemStruct?.locationCreated ?? null,
        regionLikeFields,
        error: error || (items.length ? null : (data
          ? `TikTokin post-lista ei palauttanut videoita (statusCode: ${data.statusCode ?? data.status_code ?? "?"}).`
          : `TikTokin oma post-listavastaus ei sisältänyt JSON-dataa (${String(text || "tyhjä").slice(0, 80)}).`)),
      };
    };

    // 1) Primary path: use the /api/post/item_list/ response emitted by TikTok's own frontend.
    let postApi = capturedPostResponse
      ? makePostResult(
          "TikTokin oman sivun verkkovastaus",
          capturedPostResponse.status,
          capturedPostResponse.data,
          capturedPostResponse.text
        )
      : {
          attempted: true,
          source: "TikTokin oman sivun verkkovastaus",
          httpStatus: null,
          ok: false,
          itemCount: 0,
          firstVideoId: null,
          firstVideoUrl: null,
          locationCreated: null,
          regionLikeFields: [],
          error: "TikTokin sivu ei tehnyt post/item_list-pyyntöä odotusajan kuluessa.",
        };

    // Optional fallback: if TikTok did not emit the request at all, try the same endpoint from
    // inside the live page context. This is diagnostic only; it does not replace the primary path.
    if (!postApi.ok && !capturedPostResponse && u.secUid) {
      const fallback = await page.evaluate(async ({ secUid, uniqueId }) => {
        const result = { status: null, text: "", data: null, error: null };
        try {
          const params = new URLSearchParams({ secUid, cursor: "0", count: "6" });
          const r = await fetch(`/api/post/item_list/?${params.toString()}`, {
            method: "GET",
            credentials: "include",
            headers: { accept: "application/json, text/plain, */*" },
          });
          result.status = r.status;
          result.text = await r.text();
          try { result.data = JSON.parse(result.text); } catch {}
        } catch (err) {
          result.error = String(err?.message || err);
        }
        return result;
      }, { secUid: u.secUid, uniqueId: u.uniqueId || username });

      if (fallback.data || fallback.status) {
        postApi = makePostResult(
          "Sivukontekstin fallback",
          fallback.status,
          fallback.data,
          fallback.text,
          fallback.error
        );
      }
    }

    // 2) Fallback: use a rendered profile video link if TikTok exposed one in the DOM.
    let domVideoUrl = null;
    if (!postApi.firstVideoUrl) {
      try { await page.waitForSelector('a[href*="/video/"]', { timeout: 5000 }); } catch {}
      domVideoUrl = await page.evaluate(() => {
        const links = [...document.querySelectorAll('a[href*="/video/"]')]
          .map((a) => a.href)
          .filter(Boolean);
        return links.find((href) => /\/video\/\d+/.test(href)) || null;
      });
    }

    const videoUrl = postApi.firstVideoUrl || domVideoUrl;
    let video = {
      url: videoUrl,
      httpStatus: null,
      hydrationFound: false,
      videoDetailFound: false,
      locationCreated: null,
      regionLikeFields: [],
    };

    // 3) Open one public video page and inspect its hydration JSON too.
    if (videoUrl) {
      const vp = await browser.newPage();
      await vp.setUserAgent(
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
      );
      await vp.setExtraHTTPHeaders({ "Accept-Language": "en-US,en;q=0.9" });

      const vr = await vp.goto(videoUrl, { waitUntil: "domcontentloaded", timeout: 20000 });
      const inspected = await vp.evaluate(() => {
        const el = document.querySelector("#__UNIVERSAL_DATA_FOR_REHYDRATION__");
        if (!el?.textContent) {
          return { hydrationFound: false, videoDetailFound: false, locationCreated: null, regionLikeFields: [] };
        }

        try {
          const data = JSON.parse(el.textContent);
          const detail = data?.__DEFAULT_SCOPE__?.["webapp.video-detail"];
          const item = detail?.itemInfo?.itemStruct || null;
          const hits = [];
          const seen = new WeakSet();

          const walk = (value, path = "", depth = 0) => {
            if (!value || typeof value !== "object" || depth > 7 || hits.length >= 30) return;
            if (seen.has(value)) return;
            seen.add(value);

            for (const [key, child] of Object.entries(value)) {
              const nextPath = path ? `${path}.${key}` : key;
              if (/region|locationcreated|country/i.test(key) && ["string", "number", "boolean"].includes(typeof child)) {
                hits.push({ path: nextPath, value: String(child).slice(0, 120) });
              }
              if (child && typeof child === "object") walk(child, nextPath, depth + 1);
              if (hits.length >= 30) break;
            }
          };

          walk(item);
          return {
            hydrationFound: true,
            videoDetailFound: !!item,
            locationCreated: item?.locationCreated ?? item?.location_created ?? null,
            regionLikeFields: hits,
          };
        } catch {
          return { hydrationFound: true, videoDetailFound: false, locationCreated: null, regionLikeFields: [] };
        }
      });

      video = {
        ...inspected,
        url: videoUrl,
        httpStatus: vr?.status?.() ?? null,
      };
      await vp.close();
    }

    const profileRegion = twoLetter(parsed.rawRegion);
    const postRegion = twoLetter(postApi.locationCreated);
    const videoRegion = twoLetter(video.locationCreated);
    const region = profileRegion || postRegion || videoRegion;
    const regionSource = profileRegion
      ? "TikTok-profiilidata"
      : postRegion
        ? "TikTok-postilista (locationCreated)"
        : videoRegion
          ? "TikTok-videometadata (locationCreated)"
          : null;

    const allRegionFields = [
      ...(Array.isArray(postApi.regionLikeFields) ? postApi.regionLikeFields.map((x) => ({ ...x, path: `postApi.${x.path}` })) : []),
      ...(Array.isArray(video.regionLikeFields) ? video.regionLikeFields.map((x) => ({ ...x, path: `video.${x.path}` })) : []),
    ].slice(0, 40);

    return res.status(200).json({
      regionSource,
      diagnostics: {
        httpStatus: response?.status?.() ?? null,
        regionKeyPresent: parsed.regionKeyPresent,
        rawRegion: parsed.rawRegion,
        postApiAttempted: postApi.attempted,
        postApiSource: postApi.source,
        postApiHttpStatus: postApi.httpStatus,
        postApiOk: postApi.ok,
        postApiItemCount: postApi.itemCount,
        postApiError: postApi.error,
        firstVideoId: postApi.firstVideoId,
        videoUrl: video.url,
        videoHttpStatus: video.httpStatus,
        videoHydrationFound: video.hydrationFound,
        videoDetailFound: video.videoDetailFound,
        postLocationCreated: postApi.locationCreated,
        locationCreated: video.locationCreated,
        regionLikeFields: allRegionFields,
      },
      user: {
        id: u.id ?? null,
        secUid: u.secUid ?? null,
        uniqueId: u.uniqueId ?? username,
        nickname: u.nickname ?? username,
        signature: u.signature ?? null,
        avatar: u.avatarLarger ?? u.avatarMedium ?? u.avatarThumb ?? null,
        region,
        language: u.language ?? null,
        createTime: u.createTime ?? null,
        privateAccount: u.privateAccount ?? null,
        verified: u.verified ?? null,
      },
      stats: {
        followerCount: s.followerCount ?? null,
        followingCount: s.followingCount ?? null,
        heartCount: s.heartCount ?? s.heart ?? null,
        videoCount: s.videoCount ?? null,
      },
    });
  } catch (err) {
    return res.status(502).json({ error: "TikTok-haku epäonnistui.", detail: String(err?.message || err) });
  } finally {
    if (browser) {
      try { await browser.close(); } catch {}
    }
  }
}
